#!/bin/bash
set -e

usage () {
  echo "usage: $(basename "$0") TWIKI-TO-MD-FILE"
  echo
  echo "TWIKI-TO-MD-FILE contains lines of the form:"
  echo "TWIKI-URL PATH-TO-MARKDOWN.md"
  echo "as accepted by the convert-twiki script"
  exit
}

[[ -r $1 ]] || usage

FAILURES=''
while read twiki_url md_path; do
    echo "Converting $twiki_url..."
    "$(dirname "$0")"/convert-twiki "$twiki_url" "$md_path" "$1" < /dev/null
    [ $? -eq 0 ] || FAILURES+="$twiki_url "
done < "$1"

if [[ -n "$FAILURES" ]]; then
    echo
    echo "Failed to convert the following URLs:"
    tr ' ' '\n' <<< $FAILURES
fi
