#!/bin/bash

TWIKI=$1
MARKDOWN=$2

TITLE=$(basename "$TWIKI")
ARCHIVE=archive/$TITLE

curl  "$TWIKI?raw=text" | iconv -f windows-1252 > $ARCHIVE
pandoc -f twiki -t markdown_github $ARCHIVE | osg-conversions.py > $TITLE.md

