#!/bin/bash
set -e
set -o pipefail

usage () {
  echo "usage: $(basename "$0") TWIKI-URL [PATH-TO-MARKDOWN.md]"
  exit 1
}

[[ $1 = https://twiki.opensciencegrid.org/* ]] || usage

TWIKI=$1
revpat='\?rev=([0-9]+)$'
if [[ $TWIKI =~ $revpat ]]; then
  REV=${BASH_REMATCH[1]}
  TWIKI=${TWIKI%\?rev=*}
fi
TITLE=$(basename "$TWIKI")${REV:+.r$REV}
ARCHIVE=archive/$TITLE

case $2 in
    '' ) MARKDOWN=$TITLE.md ;;
  *.md ) MARKDOWN=docs/$2 ;;
     * ) echo "PATH-TO-MARKDOWN does not end in .md" >&2
         usage ;;
esac

# optional link map file
LINK_MAP=$3

tmo_msg () (
  set +e
  timeout 60 "$@"
  local e=$?
  if [[ $e -eq 124 ]]; then
    echo "$1 command timed out" >&2
    exit $e
  fi
  return $e
)

for files in $MARKDOWN $ARCHIVE; do
    mkdir -p "$(dirname "$files")"
done

curl -s --show-error "$TWIKI?raw=text${REV:+&rev=$REV}" | iconv -f windows-1252 > "$ARCHIVE"
tmo_msg \
pandoc -f twiki -t markdown_github "$ARCHIVE" | osg-conversions.py $LINK_MAP > "$MARKDOWN"

